name: ficonsax
description: ficonsax is Iconsax which is 6000 icons in different styles or 1000 icons for each style separately available as a dart/flutter package.
version: 0.0.3
repository: https://github.com/Mastersam07/fIconsax
homepage: https://github.com/Mastersam07/fIconsax

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

# The following section is specific to Flutter.
flutter:
  fonts:
   - family: IconsaxBold
     fonts:
      - asset: fonts/IconsaxBold.ttf
   - family: IconsaxOutline
     fonts:
      - asset: fonts/IconsaxOutline.ttf
   - family: IconsaxBulk
     fonts:
      - asset: fonts/IconsaxBulk.ttf