name: ficonsax
description: ficonsax is Iconsax, ~1000 icons available in 3 styles (Bold, Bulk and Outline) as a dart/flutter package.
version: 0.0.4
repository: https://github.com/Mastersam07/fIconsax
homepage: https://github.com/Mastersam07/fIconsax

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^1.0.0
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  fonts:
   - family: IconsaxBold
     fonts:
      - asset: fonts/IconsaxBold.ttf
   - family: IconsaxOutline
     fonts:
      - asset: fonts/IconsaxOutline.ttf
   - family: IconsaxBulk
     fonts:
      - asset: fonts/IconsaxBulk.ttf