name: Test

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

env:
  flutter_version: "3.44.2"
  flutter_channel: "stable"

jobs:
  format-and-lint:
    name: Package Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: ${{ env.flutter_channel }}
          cache: true
      - name: Install dependencies
        run: flutter pub get
      - name: Format code
        run: dart format --output=none --set-exit-if-changed .
      - name: Analyze
        run: flutter analyze
      - name: Run tests
        run: flutter test --coverage
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
